apiVersion: v1
kind: Pod
metadata:
  name: zeek-worker
  namespace: kube-system
  labels:
    k8s-app: zeek
    zeek-node: worker
spec:
  serviceAccount: zeek-account
  restartPolicy: Always
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  nodeName: k8s-03
  containers:
  - name: zeek
    image: m1nl/zeek:latest
    imagePullPolicy: "Always"
    env:
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: ZEEK_NODE_TYPE
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['zeek-node']
