apiVersion: v1
kind: ServiceAccount
metadata:
  name: zeek-account
  namespace: kube-system
  labels:
    k8s-app: zeek
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: zeek-cluster-role
  namespace: kube-system
  labels:
    k8s-app: zeek
rules:
  - apiGroups:
      - extensions
      - ""
    resources:
      - namespaces
      - pods
      - events
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: zeek-cluster-role-binding
  namespace: kube-system
  labels:
    k8s-app: zeek
subjects:
  - kind: ServiceAccount
    name: zeek-account
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: zeek-cluster-role
  apiGroup: rbac.authorization.k8s.io
